workflows:
  ios-release:
    name: iOS Release Build

    environment:
      flutter: stable
      xcode: latest

    integrations:
      app_store_connect: DFT_APP

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Build iOS
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app

    publishing:
      app_store_connect:
        auth: integration