workflows:
  ios-release:
    name: iOS Release Build

    environment:
      flutter: stable
      xcode: latest

    integrations:
      app_store_connect: dft_app

    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true