workflows:
  ios-release:
    name: iOS Release

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.dftapp.hu

        certificates:
          - dft_ios_cert

        provisioning_profiles:
          - dft_profile

    scripts:
      - flutter pub get
      - flutter build ipa --release

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true